# This file stores configurations for your Shopify app.

scopes = "read_files,write_script_tags,read_script_tags,write_themes,read_themes,write_files,read_discovery,write_discovery,read_gdpr_data_request,write_fulfillments,read_fulfillments,read_markets,write_markets"
